/*
 * ============================================================================
 * UNIFIED EVENT MODEL
 * ============================================================================
 *
 * The "Browser events" section shows history and downloads together in
 * chronological order. Here entries are normalized into EVENTS with an
 * `eventType`:
 *
 *   - 'download' → a downloaded file
 *   - 'search'   → a visit to a search URL on a known engine
 *   - 'redirect' → a visit generated by a redirect (client/server)
 *   - 'visit'    → a normal navigation
 *
 * Each event has a `time` field (Unix ms) for common sorting and a `soc`
 * field with the detection analysis (computed by the provided engine).
 */

import { extractSearchQuery } from './url.js'

/** Formats a size in bytes into a readable string (KB/MB/GB). */
export function formatBytes(bytes) {
  const n = Number(bytes)
  if (!Number.isFinite(n) || n <= 0) return '—'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const exp = Math.min(Math.floor(Math.log(n) / Math.log(1024)), units.length - 1)
  const value = n / 1024 ** exp
  return `${value.toFixed(exp === 0 ? 0 : 1)} ${units[exp]}`
}

/** Metadata per event type (label + badge color). */
export const EVENT_TYPE_META = {
  visit: { label: 'Visit', color: 'slate' },
  search: { label: 'Search', color: 'cyan' },
  redirect: { label: 'Redirect', color: 'amber' },
  download: { label: 'Download', color: 'emerald' },
}

/** Classifies a history entry into an event type. */
export function historyEventType(entry) {
  if (extractSearchQuery(entry.url)) return 'search'
  if (entry.isRedirect) return 'redirect'
  return 'visit'
}

/**
 * Builds the redirect index: maps visitId → the following event in the chain
 * (the visit whose `fromVisitId` points to this visitId). Used to show
 * "→ destination page" for a redirect visit.
 */
export function buildRedirectIndex(history) {
  const nextByFromVisit = new Map()
  for (const entry of history) {
    if (entry.fromVisitId != null && entry.fromVisitId !== 0) {
      if (!nextByFromVisit.has(entry.fromVisitId)) {
        nextByFromVisit.set(entry.fromVisitId, entry)
      }
    }
  }
  return nextByFromVisit
}

/** Destination event of a redirect starting from an entry, or null. */
export function redirectTarget(entry, redirectIndex) {
  if (entry.visitId == null) return null
  return redirectIndex.get(entry.visitId) ?? null
}

/**
 * Enriches history and downloads with `eventType`, `time` and `soc`.
 * @param {object} args { history, downloads, engine } — engine from createSocEngine
 * @returns {{ historyEvents: Array, downloadEvents: Array, allEvents: Array }}
 */
export function buildEvents({ history = [], downloads = [], engine }) {
  const historyEvents = history.map((entry) => {
    const event = {
      ...entry,
      kind: 'history',
      eventType: historyEventType(entry),
      time: entry.visitTime,
    }
    event.soc = engine.analyze(event)
    return event
  })

  const downloadEvents = downloads.map((entry) => {
    const event = {
      ...entry,
      kind: 'download',
      eventType: 'download',
      time: entry.startTime,
      // `title` used for search/display common to all events
      title: entry.fileName,
    }
    event.soc = engine.analyze({
      url: entry.url,
      title: entry.fileName,
      fileName: entry.fileName,
      time: entry.startTime,
    })
    return event
  })

  // "All events": union sorted by time (most recent on top).
  const allEvents = [...historyEvents, ...downloadEvents].sort(
    (a, b) => (b.time ?? 0) - (a.time ?? 0),
  )

  return { historyEvents, downloadEvents, allEvents }
}
